apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      max_chunk_age: 1h
      wal:
        dir: /loki/wal  # WAL dizinini /loki altýna taþýdýk
    schema_config:
      configs:
      - from: 2023-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/boltdb-cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    limits_config:
      enforce_metric_name: false
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 7d
    compactor:
      working_directory: /loki/compactor
      shared_store: filesystem

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: init-loki-storage
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          mkdir -p /loki/chunks /loki/index /loki/boltdb-cache /loki/compactor /loki/wal;
          chown -R 10001:10001 /loki
        volumeMounts:
        - name: loki-storage
          mountPath: /loki
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        args:
        - -config.file=/etc/loki/loki-config.yaml
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: loki-storage
          mountPath: /loki
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: loki-storage
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observability
spec:
  selector:
    app: loki
  ports:
  - name: http
    port: 3100
    targetPort: 3100